@startuml
title Вариант 24. Entity Relationship Diagram

entity "operators" as operators {
  * operator_id : int <<PK>>
  --
  operator_name : string
}

entity "tariffs" as tariffs {
  * tariff_id : int <<PK>>
  --
  operator_id : int <<FK>>
  tariff_name : string
  price_month : int [>= 0]
}

operators ||--o{ tariffs : "предлагает"
@enduml
